// <auto-generated />
using System;
using Management_Gym_System.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Management_Gym_System.Infrastructure.Data;

#nullable disable

namespace Management_Gym_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516144220_EditGymMembershipCard")]
    partial class EditGymMembershipCard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Management_Gym_System.Models.Checkin", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("CardID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckinTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("CardID");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ExportReceipt", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("ExportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.ToTable("ExportReceipts");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ExportReceiptDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<decimal>("ExportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ExportReceiptID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ExportReceiptID");

                    b.HasIndex("ProductID");

                    b.ToTable("ExportReceiptDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Models.FinancialTransaction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("TransactionType")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StaffID");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("Management_Gym_System.Models.GymMembershipCard", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PauseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<string>("RFID_UID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ResumeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("GymMembershipCards");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ImportReceipt", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("TransactionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.HasIndex("TransactionID");

                    b.ToTable("ImportReceipts");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ImportReceiptDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ImportReceiptID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ID");

                    b.HasIndex("ImportReceiptID");

                    b.HasIndex("ProductID");

                    b.ToTable("ImportReceiptDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Models.Product", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageProduct")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int?>("ThoiHan")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ProductCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Management_Gym_System.Models.TransactionDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<decimal?>("DiscountRare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("TransactionID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VATRare")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("TransactionID");

                    b.ToTable("TransactionDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<long?>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Management_Gym_System.Models.UserRole", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Management_Gym_System.Models.Checkin", b =>
                {
                    b.HasOne("Management_Gym_System.Models.GymMembershipCard", "Card")
                        .WithMany("Checkins")
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ExportReceipt", b =>
                {
                    b.HasOne("Management_Gym_System.Models.User", "Staff")
                        .WithMany("ExportReceipts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ExportReceiptDetail", b =>
                {
                    b.HasOne("Management_Gym_System.Models.ExportReceipt", "ExportReceipt")
                        .WithMany("ExportReceiptDetails")
                        .HasForeignKey("ExportReceiptID");

                    b.HasOne("Management_Gym_System.Models.Product", "Product")
                        .WithMany("ExportReceiptDetails")
                        .HasForeignKey("ProductID");

                    b.Navigation("ExportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Management_Gym_System.Models.FinancialTransaction", b =>
                {
                    b.HasOne("Management_Gym_System.Models.User", "Customer")
                        .WithMany("CustomerTransactions")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Management_Gym_System.Models.User", "Staff")
                        .WithMany("StaffTransactions")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Management_Gym_System.Models.GymMembershipCard", b =>
                {
                    b.HasOne("Management_Gym_System.Models.Product", "Product")
                        .WithMany("GymMembershipCards")
                        .HasForeignKey("ProductID");

                    b.HasOne("Management_Gym_System.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserID");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ImportReceipt", b =>
                {
                    b.HasOne("Management_Gym_System.Models.User", "Staff")
                        .WithMany("ImportReceipts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Management_Gym_System.Models.FinancialTransaction", "FinancialTransaction")
                        .WithMany("ImportReceipts")
                        .HasForeignKey("TransactionID");

                    b.Navigation("FinancialTransaction");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ImportReceiptDetail", b =>
                {
                    b.HasOne("Management_Gym_System.Models.ImportReceipt", "ImportReceipt")
                        .WithMany("ImportReceiptDetails")
                        .HasForeignKey("ImportReceiptID");

                    b.HasOne("Management_Gym_System.Models.Product", "Product")
                        .WithMany("ImportReceiptDetails")
                        .HasForeignKey("ProductID");

                    b.Navigation("ImportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Management_Gym_System.Models.Product", b =>
                {
                    b.HasOne("Management_Gym_System.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Management_Gym_System.Models.TransactionDetail", b =>
                {
                    b.HasOne("Management_Gym_System.Models.Product", "Product")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("ProductID");

                    b.HasOne("Management_Gym_System.Models.FinancialTransaction", "FinancialTransaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionID");

                    b.Navigation("FinancialTransaction");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Management_Gym_System.Models.User", b =>
                {
                    b.HasOne("Management_Gym_System.Models.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ExportReceipt", b =>
                {
                    b.Navigation("ExportReceiptDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Models.FinancialTransaction", b =>
                {
                    b.Navigation("ImportReceipts");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Models.GymMembershipCard", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ImportReceipt", b =>
                {
                    b.Navigation("ImportReceiptDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Models.Product", b =>
                {
                    b.Navigation("ExportReceiptDetails");

                    b.Navigation("GymMembershipCards");

                    b.Navigation("ImportReceiptDetails");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Management_Gym_System.Models.User", b =>
                {
                    b.Navigation("CustomerTransactions");

                    b.Navigation("ExportReceipts");

                    b.Navigation("ImportReceipts");

                    b.Navigation("Memberships");

                    b.Navigation("StaffTransactions");
                });

            modelBuilder.Entity("Management_Gym_System.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
