// <auto-generated />
using System;
using Management_Gym_System.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Management_Gym_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260810150422_UpdateUserAndRolePermissionSchema")]
    partial class UpdateUserAndRolePermissionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.Checkin", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("CardID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckinTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CardID");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ExportReceipt", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("ExportDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.ToTable("ExportReceipts");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ExportReceiptDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ExportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ExportReceiptID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ExportReceiptID");

                    b.HasIndex("ProductID");

                    b.ToTable("ExportReceiptDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("TransactionType")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StaffID");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.GymMembershipCard", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PauseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<string>("RFID_UID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ResumeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("GymMembershipCards");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ImportReceipt", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplySource")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("TransactionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.HasIndex("TransactionID");

                    b.ToTable("ImportReceipts");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ImportReceiptDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("BatchCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ImportReceiptID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ImportReceiptID");

                    b.HasIndex("ProductID");

                    b.ToTable("ImportReceiptDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.InventoryLot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ImportDetailId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginalQuantity")
                        .HasColumnType("integer");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImportDetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryLots");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.Product", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageProduct")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int?>("ThoiHan")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanExport")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("FunctionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId", "FunctionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.SystemFunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Controller")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SystemFunctions");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.TransactionDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<decimal?>("DiscountRare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("TransactionID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VATRare")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("TransactionID");

                    b.ToTable("TransactionDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<long?>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.Checkin", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.GymMembershipCard", "Card")
                        .WithMany("Checkins")
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ExportReceipt", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.User", "Staff")
                        .WithMany("ExportReceipts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ExportReceiptDetail", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.ExportReceipt", "ExportReceipt")
                        .WithMany("ExportReceiptDetails")
                        .HasForeignKey("ExportReceiptID");

                    b.HasOne("Management_Gym_System.Domain.Entities.Product", "Product")
                        .WithMany("ExportReceiptDetails")
                        .HasForeignKey("ProductID");

                    b.Navigation("ExportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.User", "Customer")
                        .WithMany("CustomerTransactions")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Management_Gym_System.Domain.Entities.User", "Staff")
                        .WithMany("StaffTransactions")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.GymMembershipCard", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.Product", "Product")
                        .WithMany("GymMembershipCards")
                        .HasForeignKey("ProductID");

                    b.HasOne("Management_Gym_System.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserID");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ImportReceipt", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.User", "Staff")
                        .WithMany("ImportReceipts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Management_Gym_System.Domain.Entities.FinancialTransaction", "FinancialTransaction")
                        .WithMany("ImportReceipts")
                        .HasForeignKey("TransactionID");

                    b.Navigation("FinancialTransaction");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ImportReceiptDetail", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.ImportReceipt", "ImportReceipt")
                        .WithMany("ImportReceiptDetails")
                        .HasForeignKey("ImportReceiptID");

                    b.HasOne("Management_Gym_System.Domain.Entities.Product", "Product")
                        .WithMany("ImportReceiptDetails")
                        .HasForeignKey("ProductID");

                    b.Navigation("ImportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.InventoryLot", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.ImportReceiptDetail", "ImportDetail")
                        .WithMany()
                        .HasForeignKey("ImportDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Management_Gym_System.Domain.Entities.Product", "Product")
                        .WithMany("InventoryLots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportDetail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.Product", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.SystemFunction", "Function")
                        .WithMany("RolePermissions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Management_Gym_System.Domain.Entities.UserRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.TransactionDetail", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.Product", "Product")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("ProductID");

                    b.HasOne("Management_Gym_System.Domain.Entities.FinancialTransaction", "FinancialTransaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionID");

                    b.Navigation("FinancialTransaction");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.User", b =>
                {
                    b.HasOne("Management_Gym_System.Domain.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ExportReceipt", b =>
                {
                    b.Navigation("ExportReceiptDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Navigation("ImportReceipts");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.GymMembershipCard", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ImportReceipt", b =>
                {
                    b.Navigation("ImportReceiptDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.Product", b =>
                {
                    b.Navigation("ExportReceiptDetails");

                    b.Navigation("GymMembershipCards");

                    b.Navigation("ImportReceiptDetails");

                    b.Navigation("InventoryLots");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.SystemFunction", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.User", b =>
                {
                    b.Navigation("CustomerTransactions");

                    b.Navigation("ExportReceipts");

                    b.Navigation("ImportReceipts");

                    b.Navigation("Memberships");

                    b.Navigation("StaffTransactions");
                });

            modelBuilder.Entity("Management_Gym_System.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
